DELETE http://localhost:8080/events/1/register
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGV4YW1wbGUuY29tIiwiZXhwIjoxNzM3MzYyODY5LCJ1c2VySWQiOjJ9.kxSr9MaXfVCYVeLACYTe6vHCp5px7axlVQXxx2TIYFM